apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: ingress
  annotations:
    kubernetes.io/ingress.class: "traefik"
{{- if eq .Values.protocol "https" }}
    traefik.ingress.kubernetes.io/router.entrypoints: web, websecure
    # traefik.ingress.kubernetes.io/router.tls: "true"
  {{- if .Values.certresolver }}
    traefik.ingress.kubernetes.io/router.tls.certresolver: {{ .Values.certresolver | quote }}
  {{- end }}
{{- else }}
    traefik.ingress.kubernetes.io/router.entrypoints: web
{{- end }}
spec:
  rules:
    - host: "{{ .Values.domain }}.{{ required "A valid .Values.domainsuffix entry required!" .Values.domainsuffix }}"
      http:
        paths:
          - path: /
            backend:
              serviceName: api
              servicePort: www
    - host: "mq.{{ .Values.domain }}.{{ required "A valid .Values.domainsuffix entry required!" .Values.domainsuffix }}"
      http:
        paths:
          - path: /
            backend:
              serviceName: rabbitmq
              servicePort: rabbitmq-mgnt
{{- if .Values.openflow.license_key }}
    - host: "grafana.{{ .Values.domain }}.{{ required "A valid .Values.domainsuffix entry required!" .Values.domainsuffix }}"
      http:
        paths:
          - path: /
            backend:
              serviceName: grafana
              servicePort: grafana
{{- end }}
{{- if and .Values.openflow.license_key (eq .Values.prometheus.enabled true) (eq .Values.prometheus.exposed true) }}
    - host: "prometheus.{{ .Values.domain }}.{{ required "A valid .Values.domainsuffix entry required!" .Values.domainsuffix }}"
      http:
        paths:
          - path: /
            backend:
              serviceName: prometheus
              servicePort: prometheus
{{- end }}
{{- if and .Values.tlsSecret (eq .Values.protocol "https") }}
  tls:
    - secretName: {{ .Values.tlsSecret | quote }}
{{- end }}
---
{{ $ingress := (lookup "extensions/v1beta1" "Ingress" .Release.Namespace "useringress") }}
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: useringress
  annotations:
    kubernetes.io/ingress.class: traefik
{{- if eq .Values.protocol "https" }}
    traefik.ingress.kubernetes.io/router.entrypoints: web, websecure
    # traefik.ingress.kubernetes.io/router.tls: "true"
  {{- if .Values.certresolver }}
    traefik.ingress.kubernetes.io/router.tls.certresolver: {{ .Values.certresolver | quote }}
  {{- end }}
{{- else }}
    traefik.ingress.kubernetes.io/router.entrypoints: web
{{- end }}
spec:
  rules:
    - host: "random.{{ .Values.domain }}.{{ required "A valid .Values.domainsuffix entry required!" .Values.domainsuffix }}"
      http:
        paths:
          - path: /
            backend:
              serviceName: api
              servicePort: www
{{ if $ingress }}
  {{- range $k, $v := (lookup "extensions/v1beta1" "Ingress" .Release.Namespace "useringress").spec.rules }}
    {{ if ne $k 0 }}
    - host: {{ $v.host }}
      http:
        paths:
        {{- range $k1, $v1 := $v.http.paths }}
          - path: {{ $v1.path }}
            backend:
              serviceName: {{$v1.backend.serviceName }} 
              servicePort: www
        {{- end }}
    {{ end }}
  {{ end }}
{{ end }}
{{- if .Values.tlsSecret }}
  tls:
    - secretName: {{ .Values.tlsSecret }}
{{- end }}
