apiVersion: v1
kind: ServiceAccount
metadata:
  name: openflow-api-user
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: openflow-api-role
rules:
- apiGroups: ["*"]
  resources: ["pods", "deployments", "services", "ingresses", "replicasets"]
  # resources: ["*/*"]
  verbs: ["get", "watch", "list", "create", "update", "patch", "delete"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: openflow-api-rb
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: openflow-api-role
subjects:
- kind: ServiceAccount
  name: openflow-api-user
